### PR TITLE
Correct Hyperlink

### PR DESCRIPTION
**Pull request by nparashar150**
Hello Sir, I saw your website, It has this wrong link :) I hope you correct it !!
Thank You.

### CODE REVIEW

**Comment by ArunTeltia** [comment]
Yup you are right I just checked.
https://github.com/ArunTeltia/Agar-io-Clone
Can you add this link instead of the agar.io link. 
This is the link that I want other to redirect to 
Thank you for the issue reporting tho 🌸

**Comment by nparashar150** [comment]
Yeah sure , lemme add that.. !!
Now is it fine?

**Comment by ArunTeltia** [comment]
LGTM Thank you :)

**Comment by nparashar150** [comment]
Your Welcome 👍🏼:)

**Pull request merged**
